import pandas as pd
titanic_df = pd.read_csv(r"C:\Users\chukw\PycharmProjects\Pandas_Data_science\Course_Materials_Part1\Coding_Exercises\titanic.csv")
print(titanic_df.head(10))
print(type(titanic_df.age))
age = titanic_df['age']
print(age.head(10))
print(age.tail(10))
print(age.dtype)
print(age.to_frame())
print(age.shape)
print(len(age))
print(age.index)
print(age.describe())
print(age.count())
print(age.size)
print('sum',age.sum)
print(age.unique())
print(age.nunique(dropna=False))
print(age.value_counts(dropna=False))
print(titanic_df.age.idxmax())
print(titanic_df.iloc[630])
print(titanic_df.loc[630])
print(titanic_df.loc[titanic_df.age.idxmax])